name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Container start
        uses: hoverkraft-tech/compose-action@v2.0.1
      - name: Waiting for сontainer start
        run: sleep 30
      - uses: hoverkraft-tech/compose-action@v2.0.1
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Start SUT
        # Запускаем SUT,
        # имя файла SUT будет отличаться в каждой задаче.
        # & означает, что в фоновом режиме не блокируем терминал для запуска тестов,
        # обязательно должен быть для запуска SUT в CI
        run: java -jar ./artifacts/app-deadline.jar -P:jdbc.url="jdbc:mysql://localhost:3306/app" -P:jdbc.user="app" -P:jdbc.password="pass" &
      - name: Build with Gradle
        # Запускаем автотесты
        # Для проектов на базе Selenide необходимо добавить параметр для запуска браузера
        # в headless режиме -Dselenide.headless=true, параметр --info должен остаться
        run: ./gradlew test --info